apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rx3g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rx3g
    app.kubernetes.io/part-of: tkrw-pr714-0075-0034-app
  name: devfile-sample-rx3g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rx3g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rx3g
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0034-tenant/tkrw-pr714-0075-0034-app/devfile-sample-rx3g@sha256:357ea8ddd0130a6b77204c378a0c902e88ebda06707bc041c489f910242802db
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
